### ISSUE TITLE
Failed to resolve entry for package "astro-yandex-metrika"

### ISSUE THREAD

**Issue by acherkashin** [ufocoder/astro-yandex-metrika#3]
При попытке использовать компонент яндекс метрики получаю следующую ошибку.

Failed to resolve entry for package "astro-yandex-metrika". The package may have incorrect main/module/exports specified in its package.json.

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/82ccd0e2-8c34-419b-9cb6-f9032145bc67">

Устанавливал с помощью команды: `npm i astro-yandex-metrika`

package.json

```json
{
	"name": "vigorous-virgo",
	"type": "module",
	"version": "0.0.1",
	"scripts": {
		"dev": "astro dev",
		"start": "astro dev",
		"build": "astro check && astro build",
		"preview": "astro preview",
		"astro": "astro"
	},
	"dependencies": {
		"@astrojs/check": "^0.7.0",
		"@astrojs/mdx": "^3.1.3",
		"@astrojs/react": "^3.0.8",
		"@astrojs/rss": "^4.0.1",
		"@astrojs/sitemap": "^3.0.4",
		"@astrojs/tailwind": "^5.0.4",
		"@types/react": "^18.2.45",
		"@types/react-dom": "^18.2.18",
		"@vercel/analytics": "^1.2.2",
		"astro": "^4.0.7",
		"astro-yandex-metrika": "^1.0.0",
		"canvas-confetti": "^1.9.2",
		"mdast-util-to-string": "^4.0.0",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"reading-time": "^1.5.0",
		"rehype-pretty-code": "^0.13.0",
		"tailwindcss": "^3.4.0",
		"typescript": "^5.3.3"
	},
	"devDependencies": {
		"@tailwindcss/typography": "^0.5.10",
		"prettier": "^3.1.1",
		"prettier-plugin-astro": "^0.14.0",
		"prettier-plugin-tailwindcss": "^0.6.0"
	}
}
```

[Проект  тут](https://gitverse.ru/cherkalexander/cherkashin.dev)

**Comment by acherkashin** [comment]
@ufocoder [тут пул реквест](https://github.com/ufocoder/astro-yandex-metrika/pull/4) с фиксом проблемы. В `package.json` был неверно указан путь для `index.ts` файла

**Comment by ufocoder** [comment]
Спасибо! Принял PR!
Честно говоря забыл о существовании этого плагин :)
